apply Service "example_endpoint" {
  display_name = "Example service"
  check_command = "example_check"
  event_command = "auto_remove_ack"
  volatile = true
  command_endpoint = host.name
  max_check_attempts = 1
  assign where host.vars.example_endpoint
}
