object EventCommand "auto_remove_ack" {
  import "plugin-event-command"
  command = [ PluginDir + "/auto_remove_ack" ]

  env = {
    APIUSER = "auto-remove-ack"
    APIPASS = "replace-with-a-secret"
    APIURL  = "https://icinga.example.org:5665"
  }

  arguments = {
    "--host" = "$host.name$"
    "--service" = "$service.name$"
    "--state" = "$service.state$"
    "--state_id" = "$service.state_id$"
    "--output" = "$service.output$"
    "--ack" = "$service.acknowledgement$"
  }
}
